// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutMainImport } from './routes/_layout-main'
import { Route as LayoutAuthImport } from './routes/_layout-auth'

// Create Virtual Routes

const LayoutMainIndexLazyImport = createFileRoute('/_layout-main/')()
const LayoutMainRecordsLazyImport = createFileRoute('/_layout-main/records')()
const LayoutMainCategoriesLazyImport = createFileRoute(
  '/_layout-main/categories',
)()
const LayoutMainAboutLazyImport = createFileRoute('/_layout-main/about')()
const LayoutAuthLoginLazyImport = createFileRoute('/_layout-auth/login')()

// Create/Update Routes

const LayoutMainRoute = LayoutMainImport.update({
  id: '/_layout-main',
  getParentRoute: () => rootRoute,
} as any)

const LayoutAuthRoute = LayoutAuthImport.update({
  id: '/_layout-auth',
  getParentRoute: () => rootRoute,
} as any)

const LayoutMainIndexLazyRoute = LayoutMainIndexLazyImport.update({
  path: '/',
  getParentRoute: () => LayoutMainRoute,
} as any).lazy(() =>
  import('./routes/_layout-main/index.lazy').then((d) => d.Route),
)

const LayoutMainRecordsLazyRoute = LayoutMainRecordsLazyImport.update({
  path: '/records',
  getParentRoute: () => LayoutMainRoute,
} as any).lazy(() =>
  import('./routes/_layout-main/records.lazy').then((d) => d.Route),
)

const LayoutMainCategoriesLazyRoute = LayoutMainCategoriesLazyImport.update({
  path: '/categories',
  getParentRoute: () => LayoutMainRoute,
} as any).lazy(() =>
  import('./routes/_layout-main/categories.lazy').then((d) => d.Route),
)

const LayoutMainAboutLazyRoute = LayoutMainAboutLazyImport.update({
  path: '/about',
  getParentRoute: () => LayoutMainRoute,
} as any).lazy(() =>
  import('./routes/_layout-main/about.lazy').then((d) => d.Route),
)

const LayoutAuthLoginLazyRoute = LayoutAuthLoginLazyImport.update({
  path: '/login',
  getParentRoute: () => LayoutAuthRoute,
} as any).lazy(() =>
  import('./routes/_layout-auth/login.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout-auth': {
      preLoaderRoute: typeof LayoutAuthImport
      parentRoute: typeof rootRoute
    }
    '/_layout-main': {
      preLoaderRoute: typeof LayoutMainImport
      parentRoute: typeof rootRoute
    }
    '/_layout-auth/login': {
      preLoaderRoute: typeof LayoutAuthLoginLazyImport
      parentRoute: typeof LayoutAuthImport
    }
    '/_layout-main/about': {
      preLoaderRoute: typeof LayoutMainAboutLazyImport
      parentRoute: typeof LayoutMainImport
    }
    '/_layout-main/categories': {
      preLoaderRoute: typeof LayoutMainCategoriesLazyImport
      parentRoute: typeof LayoutMainImport
    }
    '/_layout-main/records': {
      preLoaderRoute: typeof LayoutMainRecordsLazyImport
      parentRoute: typeof LayoutMainImport
    }
    '/_layout-main/': {
      preLoaderRoute: typeof LayoutMainIndexLazyImport
      parentRoute: typeof LayoutMainImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  LayoutAuthRoute.addChildren([LayoutAuthLoginLazyRoute]),
  LayoutMainRoute.addChildren([
    LayoutMainAboutLazyRoute,
    LayoutMainCategoriesLazyRoute,
    LayoutMainRecordsLazyRoute,
    LayoutMainIndexLazyRoute,
  ]),
])
